export class Constants{
    public static getForm(){
        return {
            "type": "form",
            "name": "Employer",
            "entity": "WgmPerson",
            "loadMethod": {
                "name": null,
                "mode": "All",
                "loadPrimaryObject": false,
                "loadMapping": null
            },
            "control": {
                "type": "StackLayout",
                "width": null,
                "minWidth": 0,
                "minHeight": 0,
                "visibility": null,
                "marginTop": 0,
                "marginRight": 0,
                "marginBottom": 0,
                "marginLeft": 0,
                "paddingTop": 0,
                "paddingRight": 0,
                "paddingBottom": 0,
                "paddingLeft": 0,
                "height": null,
                "backgroundColor": null,
                "horizontalAlignment": null,
                "verticalAlignment": null,
                "row": null,
                "col": null,
                "rowSpan": 0,
                "colSpan": 0,
                "orientation": null,
                "controls": [
                    {
                        "type": "Label",
                        "ID": "Label1"
                    },
                    {
                        "type": "Caption",
                        "width": null,
                        "minWidth": 0,
                        "minHeight": 0,
                        "visibility": null,
                        "marginTop": 0,
                        "marginRight": 0,
                        "marginBottom": 0,
                        "marginLeft": 0,
                        "paddingTop": 0,
                        "paddingRight": 0,
                        "paddingBottom": 0,
                        "paddingLeft": 0,
                        "height": null,
                        "backgroundColor": null,
                        "horizontalAlignment": null,
                        "verticalAlignment": null,
                        "row": null,
                        "col": null,
                        "rowSpan": 0,
                        "colSpan": 0,
                        "ID": "Caption1"
                    },
                    {
                        "type": "Input",
                        "width": null,
                        "minWidth": 0,
                        "minHeight": 0,
                        "visibility": null,
                        "marginTop": 0,
                        "marginRight": 0,
                        "marginBottom": 0,
                        "marginLeft": 0,
                        "paddingTop": 0,
                        "paddingRight": 0,
                        "paddingBottom": 0,
                        "paddingLeft": 0,
                        "height": null,
                        "backgroundColor": null,
                        "horizontalAlignment": null,
                        "verticalAlignment": null,
                        "row": null,
                        "col": null,
                        "rowSpan": 0,
                        "colSpan": 0,
                        "ID": "Input1"
                    },
                    {
                        "type": "Label",
                        "ID": "Label2"
                    },
                    {
                                "type": "ScrollView",
                                "width": null,
                                "minWidth": 0,
                                "minHeight": 0,
                                "visibility": null,
                                "marginTop": 0,
                                "marginRight": 0,
                                "marginBottom": 0,
                                "marginLeft": 0,
                                "paddingTop": 0,
                                "paddingRight": 0,
                                "paddingBottom": 0,
                                "paddingLeft": 0,
                                "height": null,
                                "backgroundColor": "#000000",
                                "horizontalAlignment": null,
                                "verticalAlignment": null,
                                "row": null,
                                "col": null,
                                "rowSpan": 0,
                                "colSpan": 0,
                                "orientation": null,
                                "control": {
                                    "type": "GridLayout",
                                    "width": null,
                                    "minWidth": 0,
                                    "minHeight": 0,
                                    "visibility": null,
                                    "marginTop": 10,
                                    "marginRight": 0,
                                    "marginBottom": 0,
                                    "marginLeft": 0,
                                    "paddingTop": 0,
                                    "paddingRight": 0,
                                    "paddingBottom": 0,
                                    "paddingLeft": 0,
                                    "height": null,
                                    "backgroundColor": "#ff0000",
                                    "horizontalAlignment": null,
                                    "verticalAlignment": null,
                                    "row": null,
                                    "col": null,
                                    "rowSpan": 0,
                                    "colSpan": 0,
                                    "columns": "star,star",
                                    "rows": "star,star",
                                    "controls": [
                                        {
                                            "type": "Caption",
                                            "width": null,
                                            "minWidth": 0,
                                            "minHeight": 0,
                                            "visibility": null,
                                            "marginTop": 0,
                                            "marginRight": 0,
                                            "marginBottom": 0,
                                            "marginLeft": 0,
                                            "paddingTop": 0,
                                            "paddingRight": 0,
                                            "paddingBottom": 0,
                                            "paddingLeft": 0,
                                            "height": null,
                                            "backgroundColor": null,
                                            "horizontalAlignment": null,
                                            "verticalAlignment": null,
                                            "row": 0,
                                            "col": 0,
                                            "rowSpan": 0,
                                            "colSpan": 0,
                                            "ID": "Caption3"
                                        },
                                        {
                                            "type": "Label",
                                            "ID": "Label3",
                                            "row": 0,
                                            "col": 1,
                                        },
                                        {
                                            "type": "Input",
                                            "width": null,
                                            "minWidth": 0,
                                            "minHeight": 0,
                                            "visibility": null,
                                            "marginTop": 0,
                                            "marginRight": 0,
                                            "marginBottom": 0,
                                            "marginLeft": 0,
                                            "paddingTop": 0,
                                            "paddingRight": 0,
                                            "paddingBottom": 0,
                                            "paddingLeft": 0,
                                            "height": null,
                                            "backgroundColor": null,
                                            "horizontalAlignment": null,
                                            "verticalAlignment": null,
                                            "row": 1,
                                            "col": 0,
                                            "rowSpan": 0,
                                            "colSpan": 0,
                                            "ID": "Input2"
                                        },
                                        {
                                            "type": "Caption",
                                            "width": null,
                                            "minWidth": 0,
                                            "minHeight": 0,
                                            "visibility": null,
                                            "marginTop": 0,
                                            "marginRight": 0,
                                            "marginBottom": 0,
                                            "marginLeft": 0,
                                            "paddingTop": 0,
                                            "paddingRight": 0,
                                            "paddingBottom": 0,
                                            "paddingLeft": 0,
                                            "height": null,
                                            "backgroundColor": null,
                                            "horizontalAlignment": null,
                                            "verticalAlignment": null,
                                            "row": 1,
                                            "col": 1,
                                            "rowSpan": 0,
                                            "colSpan": 0,
                                            "ID": "Caption4"
                                        }
                                    ],
                                    "ID": "GridLayout2"
                                },
                                "ID": "ScrollView1"
                            },
                ],
                "ID": "stackLayout"
            }
        }
        
    }
}